repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: no-commit-to-branch  # prevent direct commits to main branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-toml
  - repo: local
    hooks:
    - id: lint
      name: Lint
      entry: make lint
      types: [python]
      language: system
      pass_filenames: false
