site_name: ArFiSettings
site_url: https://py-art.github.io/arfi-settings
repo_url: https://github.com/py-art/arfi-settings
edit_uri: blob/main/docs

docs_dir: docs/
exclude_docs: overrides/

theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.select
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github-alt
  favicon: assets/images/favicon.ico
  logo: assets/images/logo-white.png

nav:
  - ArFiSettings:
    - Introduction: index.md
    - Why and what's next: about/why.md
    - Library Goals: about/library_goals.md
    - about/installation.md
    - about/app_configuration.md
    - Reverse inheritance: about/reverse_inheritance.md
    - Debug mode: about/debug_mode.md
  - Usage:
    - usage/config.md
    - usage/pyproject.md
    - usage/handlers.md
    - usage/readers.md
    - usage/cli.md
    - usage/connectors.md
  - Examples:
    - examples/custom_reader_and_handler.md
    - examples/new_file_extentions.md
  - Changelog: changelog.md

plugins:
  - search: {}
  - i18n:
      docs_structure: folder
      languages:
        - locale: ru
          default: true
          name: Russian
          build: true
          nav_translations:
            Introduction: Введение
            Why and what's next: Почему, зачем и что дальше
            Library Goals: Цели библиотеки
            Reverse inheritance: Обратное наследование
            Debug mode: Режим отладки
            Usage: Использование
            Examples: Примеры
        - locale: en
          name: English
          build: true

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

copyright: Copyright &copy; 2024 Artur Filin
