site_name: ArFiSettings
site_url: https://py-art.github.io/arfi-settings
repo_url: https://github.com/py-art/arfi-settings
edit_uri: blob/main/docs

docs_dir: docs/
exclude_docs: overrides/

theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: '(prefers-color-scheme: light)'
      # scheme: default
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      # scheme: slate
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
  - ArFiSettings:
    - Introduction: index.md
    - Why and what's next: about/why.md
    - Installation: about/installation.md
  - Usage:
    - usage/config.md
    - usage/pyproject.md
  - Changelog: changelog.md

plugins:
  - search: {}
  - i18n:
      docs_structure: folder
      languages:
        - locale: ru
          default: true
          name: Russian
          build: true
          nav_translations:
            Introduction: Введение
            Why and what's next: Почему, зачем и что дальше
            Installation: Установка
            Usage: Применение
        - locale: en
          name: English
          build: true

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets

extra:
  analytics:
    provider: google
    property: G-RP4PM5PGLN

copyright: Copyright &copy; 2024 Artur Filin
